CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(50)                            NOT NULL,
    surname  VARCHAR(50)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(64)                            NOT NULL,
    phone    VARCHAR(20),
    role     VARCHAR(20),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CHECK ( role IN ('ADMIN', 'CUSTOMER', 'STAFF', 'OWNER'))
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE TABLE restaurant
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(120)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    time_zone  VARCHAR(50)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    version    INTEGER,
    CONSTRAINT pk_restaurant PRIMARY KEY (id)
);


CREATE TABLE table_group
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_tablegroup PRIMARY KEY (id)
);


CREATE TABLE restaurant_table
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT                                  NOT NULL,
    table_name    VARCHAR(20)                             NOT NULL,
    min_capacity  INTEGER                                 NOT NULL,
    max_capacity  INTEGER                                 NOT NULL,
    group_id      BIGINT,
    CONSTRAINT pk_restaurant_table PRIMARY KEY (id)
);

ALTER TABLE restaurant_table
    ADD CONSTRAINT FK_RESTAURANT_TABLE_ON_GROUP FOREIGN KEY (group_id) REFERENCES table_group (id);

ALTER TABLE restaurant_table
    ADD CONSTRAINT FK_RESTAURANT_TABLE_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);


CREATE TABLE policy
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT,
    CONSTRAINT pk_policy PRIMARY KEY (id)
);

ALTER TABLE policy
    ADD CONSTRAINT uc_policy_restaurant UNIQUE (restaurant_id);

ALTER TABLE policy
    ADD CONSTRAINT FK_POLICY_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);

CREATE TABLE schedules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    policy_id   BIGINT                                  NOT NULL,
    day_of_week VARCHAR(255)                            NOT NULL,
    start_time  time WITHOUT TIME ZONE                  NOT NULL,
    end_time    time WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_schedules PRIMARY KEY (id)
);

ALTER TABLE schedules
    ADD CONSTRAINT FK_SCHEDULES_ON_POLICY FOREIGN KEY (policy_id) REFERENCES policy (id);

CREATE TABLE reservation
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT                                  NOT NULL,
    table_id      BIGINT                                  NOT NULL,
    start_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expired_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    party_size    INTEGER                                 NOT NULL,
    duration_min  INTEGER                                 NOT NULL,
    status        VARCHAR(255),
    user_id       BIGINT                                  NOT NULL,
    special_notes VARCHAR(250),
    created       TIMESTAMP WITHOUT TIME ZONE,
    modified      TIMESTAMP WITHOUT TIME ZONE,
    version       INTEGER,
    CONSTRAINT pk_reservation PRIMARY KEY (id),
    CHECK ( status IN ('PENDING', 'HOLD', 'CONFIRMED', 'SEATED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'EXPIRED'))
);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_TABLE FOREIGN KEY (table_id) REFERENCES restaurant_table (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);