ALTER TABLE policy
    ALTER COLUMN restaurant_id SET NOT NULL;

ALTER TABLE policy
    DROP CONSTRAINT FK_POLICY_ON_RESTAURANT;

ALTER TABLE policy
    ADD CONSTRAINT FK_POLICY_ON_RESTAURANT
        FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)
            ON DELETE CASCADE;